import React, { useState } from "react";
import Head from "next/head";
import Modal from "../components/Modal/Modal";
import styles from "../styles/Home.module.css";

import { useRouter } from "next/router";

export default function Home() {
    let router = useRouter();

    const [showModal, setShowModal] = useState(false);

    // let gretting = router.locale.
    return (
        <div>
            <Head>
                <title>Ledgis - The New Block Order</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <button
                    className={styles.btn}
                    onClick={() => setShowModal(true)}
                >
                    Modal
                </button>

                <Modal show={showModal} onClose={() => setShowModal(false)}>
                    모달창 내용
                </Modal>
            </main>
        </div>
    );
}
