import React, { useState } from "react";
import Head from "next/head";
// import Modal from "../componnents/Modal";
import styles from "../styles/Home.module.css";

import { useTranslation, useLanguageQuery } from "next-export-i18n";

export default function Home() {
    const { t } = useTranslation();
    const [query] = useLanguageQuery();
    const [showModal, setShowModal] = useState(false);
    return (
        <div>
            <Head>
                <title>Ledgis - The New Block Order</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>{t("ui.languageSwitcher")}</h1>
                <h2>{t("intro.introText")}</h2>
                <button
                    className={styles.btn}
                    onClick={() => setShowModal(true)}
                >
                    Modal
                </button>
                {/* {showModal && (
                    <Modal onClose={() => setShowModal(false)} show={showModal}>
                        hihi
                    </Modal>
                )} */}
            </main>
        </div>
    );
}
