import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import {
    useTranslation,
    useLanguageQuery,
    LanguageSwitcher,
} from "next-export-i18n";

export default function Home() {
    const { t } = useTranslation();
    const [query] = useLanguageQuery();

    return (
        <div className={styles.container}>
            <Head>
                <title>Ledgis - The New Block Order</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>{t("ui.languageSwitcher")}</h1>
                <h2>{t("intro.introText")}</h2>
                <div className={styles.card} href="/Modal">
                    Modal Button
                </div>
            </main>
        </div>
    );
}
